<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" /><meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content="Exceptions" />
<meta property="og:type" content="website" />
<meta property="og:url" content="https://docs.python.org/3/library/asyncio-exceptions.xhtml" />
<meta property="og:site_name" content="Python documentation" />
<meta property="og:description" content="Source code: Lib/asyncio/exceptions.py[https://github.com/python/cpython/tree/3.13/Lib/asyncio/exceptions.py]" />
<meta property="og:image" content="https://docs.python.org/3/_static/og-image.png" />
<meta property="og:image:alt" content="Python documentation" />
<meta name="description" content="Source code: Lib/asyncio/exceptions.py[https://github.com/python/cpython/tree/3.13/Lib/asyncio/exceptions.py]" />
<meta property="og:image:width" content="200" />
<meta property="og:image:height" content="200" />
<meta name="theme-color" content="#3776ab" />

    <title>Exceptions</title>
    <link rel="stylesheet" type="text/css" href="../_static/pygments.css" />
    <link rel="stylesheet" type="text/css" href="../_static/epub.css" />
    
    <link rel="canonical" href="https://docs.python.org/3/library/asyncio-exceptions.html" />
    
      
    

    
    <style>
      @media only screen {
        table.full-width-table {
            width: 100%;
        }
      }
    </style>
 

  </head><body>


    <div class="document">
      <div class="documentwrapper">
          <div class="body" role="main">
            
  <section id="exceptions">
<span id="asyncio-exceptions"></span><h1>Exceptions</h1>
<p><strong>Source code:</strong> <a class="extlink-source reference external" href="https://github.com/python/cpython/tree/3.13/Lib/asyncio/exceptions.py">Lib/asyncio/exceptions.py</a><span class="link-target"> [https://github.com/python/cpython/tree/3.13/Lib/asyncio/exceptions.py]</span></p>
<hr class="docutils" />
<dl class="py exception">
<dt class="sig sig-object py" id="asyncio.TimeoutError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">asyncio.</span></span><span class="sig-name descname"><span class="pre">TimeoutError</span></span></dt>
<dd><p>A deprecated alias of <a class="reference internal" href="exceptions.xhtml#TimeoutError" title="TimeoutError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">TimeoutError</span></code></a>,
raised when the operation has exceeded the given deadline.</p>
<div class="versionchanged">
<p><span class="versionmodified changed">Changed in version 3.11: </span>This class was made an alias of <a class="reference internal" href="exceptions.xhtml#TimeoutError" title="TimeoutError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">TimeoutError</span></code></a>.</p>
</div>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="asyncio.CancelledError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">asyncio.</span></span><span class="sig-name descname"><span class="pre">CancelledError</span></span></dt>
<dd><p>The operation has been cancelled.</p>
<p>This exception can be caught to perform custom operations
when asyncio Tasks are cancelled.  In almost all situations the
exception must be re-raised.</p>
<div class="versionchanged">
<p><span class="versionmodified changed">Changed in version 3.8: </span><a class="reference internal" href="#asyncio.CancelledError" title="asyncio.CancelledError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">CancelledError</span></code></a> is now a subclass of <a class="reference internal" href="exceptions.xhtml#BaseException" title="BaseException"><code class="xref py py-class docutils literal notranslate"><span class="pre">BaseException</span></code></a> rather than <a class="reference internal" href="exceptions.xhtml#Exception" title="Exception"><code class="xref py py-class docutils literal notranslate"><span class="pre">Exception</span></code></a>.</p>
</div>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="asyncio.InvalidStateError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">asyncio.</span></span><span class="sig-name descname"><span class="pre">InvalidStateError</span></span></dt>
<dd><p>Invalid internal state of <a class="reference internal" href="asyncio-task.xhtml#asyncio.Task" title="asyncio.Task"><code class="xref py py-class docutils literal notranslate"><span class="pre">Task</span></code></a> or <a class="reference internal" href="asyncio-future.xhtml#asyncio.Future" title="asyncio.Future"><code class="xref py py-class docutils literal notranslate"><span class="pre">Future</span></code></a>.</p>
<p>Can be raised in situations like setting a result value for a
<em>Future</em> object that already has a result value set.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="asyncio.SendfileNotAvailableError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">asyncio.</span></span><span class="sig-name descname"><span class="pre">SendfileNotAvailableError</span></span></dt>
<dd><p>The “sendfile” syscall is not available for the given
socket or file type.</p>
<p>A subclass of <a class="reference internal" href="exceptions.xhtml#RuntimeError" title="RuntimeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">RuntimeError</span></code></a>.</p>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="asyncio.IncompleteReadError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">asyncio.</span></span><span class="sig-name descname"><span class="pre">IncompleteReadError</span></span></dt>
<dd><p>The requested read operation did not complete fully.</p>
<p>Raised by the <a class="reference internal" href="asyncio-stream.xhtml#asyncio-streams"><span class="std std-ref">asyncio stream APIs</span></a>.</p>
<p>This exception is a subclass of <a class="reference internal" href="exceptions.xhtml#EOFError" title="EOFError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">EOFError</span></code></a>.</p>
<dl class="py attribute">
<dt class="sig sig-object py" id="asyncio.IncompleteReadError.expected">
<span class="sig-name descname"><span class="pre">expected</span></span></dt>
<dd><p>The total number (<a class="reference internal" href="functions.xhtml#int" title="int"><code class="xref py py-class docutils literal notranslate"><span class="pre">int</span></code></a>) of expected bytes.</p>
</dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="asyncio.IncompleteReadError.partial">
<span class="sig-name descname"><span class="pre">partial</span></span></dt>
<dd><p>A string of <a class="reference internal" href="stdtypes.xhtml#bytes" title="bytes"><code class="xref py py-class docutils literal notranslate"><span class="pre">bytes</span></code></a> read before the end of stream was reached.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="asyncio.LimitOverrunError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">asyncio.</span></span><span class="sig-name descname"><span class="pre">LimitOverrunError</span></span></dt>
<dd><p>Reached the buffer size limit while looking for a separator.</p>
<p>Raised by the <a class="reference internal" href="asyncio-stream.xhtml#asyncio-streams"><span class="std std-ref">asyncio stream APIs</span></a>.</p>
<dl class="py attribute">
<dt class="sig sig-object py" id="asyncio.LimitOverrunError.consumed">
<span class="sig-name descname"><span class="pre">consumed</span></span></dt>
<dd><p>The total number of to be consumed bytes.</p>
</dd></dl>

</dd></dl>

</section>


            <div class="clearer"></div>
          </div>
      </div>
      <div class="clearer"></div>
    </div>
  </body>
</html>